import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/admin/',
          '/api/',
          '/_next/',
          '/private/',
          '/temp/',
          '/uploads/',
          '/payments/',
          '/payment/',
          '/cart/',
          '/profile/',
          '/bank-transactions/',
          '/login/',
          '/register/',
          '/forgot-password/',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/admin/',
          '/api/',
          '/_next/',
          '/private/',
          '/temp/',
          '/uploads/',
          '/payments/',
          '/payment/',
          '/cart/',
          '/profile/',
          '/bank-transactions/',
          '/login/',
          '/register/',
          '/forgot-password/',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: '/',
        disallow: [
          '/admin/',
          '/api/',
          '/_next/',
          '/private/',
          '/temp/',
          '/uploads/',
          '/payments/',
          '/payment/',
          '/cart/',
          '/profile/',
          '/bank-transactions/',
          '/login/',
          '/register/',
          '/forgot-password/',
        ],
      },
    ],
    sitemap: 'https://polysmart.nghiaht.io.vn/sitemap.xml',
    host: 'https://polysmart.nghiaht.io.vn',
  };
} 